name: BlockBattles
version: '1.0-SNAPSHOT'
main: com.person98.blockbattlesbase.BlockBattles
api-version: 1.19
author: person98
description: BlockBattles.
commands:
  warpundo:
    description: Undo the last Firewarp or Icewarp
    usage: /warpundo <fire|ice>
  openwarpgui:
    description: Open the Warp GUI
    usage: /openwarpgui